#!/usr/bin/python

import testrunner
import z3seq
#import z3str3
import cvc4
#import norn
import woorpje
#import woorpje_waitinglist
#import woorpje_vartermratio
import woorpje_heuristics

#import sloth
import summarygenerators
from datetime import datetime

tracks = ["track01","track02","track03","track04","track05"]
timeout = 30

solvers = {#'z3str3' : z3str3.run,
           #'z3seq' : z3seq.run,
           #'cvc4' : cvc4.run,
           #'norn' :  norn.run,
           #'woorpje' :  woorpje.run
           'heuristic_woorpje' : woorpje_heuristics.run
           #'heuristic_waitingList' : woorpje_waitinglist.run,
           #'heuristic_varTermRatio' : woorpje_vartermratio.run
}

summaries = [summarygenerators.terminalResult,
             #summarygenerators.cactusPlot
]


timestamp = datetime.timestamp(datetime.now())

outputfile = open("results/results_"+str(timestamp)+".csv",'w')
testrunner.runTestSetup (tracks,solvers,summaries,outputfile,timeout)
