#!/usr/bin/python

from runners.multi import TheRunner as testrunner
import utils
import storage
import voting.majority as voting
import tools.z3seq
import tools.z3str3
import tools.cvc4
import tools.woorpjeSMT
import tools.trau
import tools.woorpje_heuristics
import tools.dummy


#import models.woorpje.track01

import models.woorpje
import models.kaluza
import models.PyEx
import models.pisa
import models.nornbenchmarks
import models.stringfuzz
import models.z3_regression
import models.appscan
import models.slothtests
import models.light
import models.Leetcode
import startwebserver




import summarygenerators

tracks = (models.PyEx.getTrackData () +
          models.pisa.getTrackData ("Pisa") +
          models.nornbenchmarks.getTrackData ("Norn Benchmarks") +
          models.light.getTrackData("Trau Light")+
	        models.Leetcode.getTrackData ("Leetcode Strings") + 
          models.appscan.getTrackData ( "IBM Appscan") + 
          models.slothtests.getTrackData ("Sloth Tests")
	        models.woorpje.getTrackData ("Woorpje Word Equations") +
          models.kaluza.getTrackData ("Kaluza") +
          models.stringfuzz.getTrackData ("StringFuzz Tests") +
          models.z3_regression.getTrackData("z3Str3 Regression Test")+
          []
)
#solvers = {
#    'z3str3' : tools.z3str3.run,
#    'z3seq' : tools.z3seq.run,
#    'cvc4' : tools.cvc4.run,
#    'trau' : toQols.trau.run
    #'norn' :  tools.norn.run,
    #'woorpje' :  tools.woorpjeSMT.run
#}
smtsolvers = ["cvc4"]

solvers = {}
for s in [tools.z3seq,
          tools.z3str3,
          tools.cvc4,
          #tools.woorpjeSMT
          tools.trau,
          #tools.dummy
]:
    s.addRunner (solvers)
#tools.woorpje_heuristics.addRunners ("variableTermRatio",smtsolvers,3.14,solvers)

summaries = [summarygenerators.terminalResult
]
timeout = 30 
ploc = utils.JSONProgramConfig ()

store = storage.SQLiteDB ("RP")
summaries = [
    summarygenerators.terminalResult,
    store.postTrackUpdate
]
testrunner().runTestSetup (tracks,solvers,voting.MajorityVoter(),summaries,store,timeout,ploc)
startwebserver.Server (store.getDB ()).startServer ()
