#!/usr/bin/python

import testrunner
import z3seq
import z3str3
import cvc4
import woorpje
import summarygenerators


tracks = ["track01","track02","track03","track04","track05"]
timeout = 30

solvers = {'z3str3' : z3str3.run,
           'z3seq' : z3seq.run,
           'cvc4' : cvc4.run,
           'woorpje' :  woorpje.run
}

summaries = [summarygenerators.terminalResult,
             summarygenerators.cactusPlot
]

    
outputfile = open("sat19.csv",'w')
testrunner.runTestSetup (tracks,solvers,summaries,outputfile,timeout)
