#!/usr/bin/python

import testrunnermulti
import z3seq
import z3str3
import cvc4
#import norn
#import woorpjeSMT
#import woorpje_heuristics
#import kaluzaWoorpje
#import track01
#import track02
#import track03
#import track04
#import track05
import z3_regression


#import sloth
import summarygenerators
from datetime import datetime

tracks = [z3_regression.trackdata]
timeout = 30

solvers = {
    'z3str3' : z3str3.run,
    'z3seq' : z3seq.run,
    'cvc4' : cvc4.run,
}

smtsolvers = ["z3seq","cvc4","z3str3"]

#woorpje_heuristics.addRunners ("variableTermRatio",smtsolvers,3.14,solvers)
#woorpje_heuristics.addRunners ("variableTermRatio",smtsolvers,0.15,solvers)
#woorpje_heuristics.addRunners ("variableTermRatio",smtsolvers,1.12358,solvers)

#woorpje_heuristics.addRunners ("waitingListLimit",smtsolvers,314,solvers)
#woorpje_heuristics.addRunners ("waitingListLimit",smtsolvers,15,solvers)
#woorpje_heuristics.addRunners ("waitingListLimit",smtsolvers,1123,solvers)

#woorpje_heuristics.addRunners ("equationGrowth",smtsolvers,0.15,solvers)
#woorpje_heuristics.addRunners ("equationGrowth",smtsolvers,1.075,solvers)
#woorpje_heuristics.addRunners ("equationGrowth",smtsolvers,2.0,solvers)

#woorpje_heuristics.addRunners ("equationLength",smtsolvers,2,solvers)
#woorpje_heuristics.addRunners ("equationLength",smtsolvers,20,solvers)
#woorpje_heuristics.addRunners ("equationLength",smtsolvers,400,solvers)

#woorpje_heuristics.addRunners ("none",smtsolvers,5,solvers)



summaries = [summarygenerators.terminalResult,
             #summarygenerators.cactusPlot
]


timestamp = datetime.timestamp(datetime.now())

outputfile = open("results/results_"+str(timestamp)+".csv",'w')
testrunnermulti.runTestSetup (tracks,solvers,summaries,outputfile,timeout)
