Variables {BCAD}
Terminals {acbd}
Equation: BdCcabcaadccccdbcbcb = bddcdbacddbdaaabdcaaccccbaadbacabcaadccccdbcbcb
Equation: abbaaabcdabbdbbcddbBddddaaa = abbaaabcdabbdbbcDbabadaddaaccabaabddddaaa
Equation: bcaaaabbaadbcccaacbcbadadaacdaccdbdbdaccaaaccbc = bcaaaabbaadbcccaacbcbadadaacdaAbdbdaccaaaccbc
Equation: dadaabaabacadabcdabbdcaacddcaddcdaAdabddccaca = dadaabaabacadabcdabbdcaacddcaddcdaAdabddccaca
Equation: dabcaabbccdbddbddbbbbacaddbdcacabacddddcaadcabb = dabcaabbAbddbddbbbbacaddbdcacabacddddcaadcabb
Equation: bbdaadbcababdbaabbccaaabbaabbbaccbdaaAbbcdadc = bbdaadbcababdbaabbccaaabbaabbbaccbdaaAbbcdadc
Equation: aacbbbaccccabcbaaabaacccaabcdacbadacdaadcbdcA = aacbbbaccccabcbaaabaacccaabcdacbadacdaadcbdcccd
Equation: bcdcbcbdbaddabdbbcbbaaddaadbcdbacdbbaccdabcaaab = bcdcbcbdbaddabdbbcbbaaddaadbcdbacdbbaAabcaaab
Equation: adccbcacbaaabbbbbcdbdaadcdccdcaacdaccbacabdbcdc = adccbcacbaaabbbbbcdbdaadcdAcaacdaccbacabdbcdc
SatGlucose(100)